FROM node:16-alpine
USER node
# -p create directory only if it doesn't exist
RUN mkdir -p /home/node/app
# working dir inside a container 
WORKDIR '/home/node/app'

COPY --chown=node:node ./package.json ./
RUN npm install

COPY --chown=node:node ./ ./

CMD ["npm", "run", "start"]
