version: 2.1
orbs:
  node: circleci/node@5.0.2
  # heroku: circleci/heroku@1.2.6

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: 
          command: npm run test 
          name: Run tests
      - run:
          command: npm run build
          name: Build app 
      - persist_to_workspace:
          root: .          
          paths:
            - build/* 
  deploy:
    working_directory: ~/project
    machine:
      image: ubuntu-2004:202010-01
      # deployment to Heroku
      # - checkout
      # - heroku/deploy-via-git:
      #   force: true
      #          

      # deployment to reactcode.pl

    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - add_ssh_keys:
            fingerprints:
              - "2a:ed:4a:84:3a:ef:67:f3:90:b6:a8:a8:47:d5:28:38"
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST |
            echo "Byem tu fiutku" >> file.txt
            # echo $SSH_SUDO_PASSWORD | 
            # sudo -S cp -rf ./build /usr/share/nginx/html
            exit

workflows:
  build_test_deploy: 
    jobs:
      - build_and_test
      - deploy:
          requires:
          - build_and_test
        
          filters:
            # tags:
            #   only: /^v.*/
            branches:
              only: master
    
    
