version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: 
          command: npm run test 
          name: Run tests
      - run:
          command: npm run build
          name: Build app 
      # - persist_to_workspace:
      #     root: ~/frontend
      #     paths:
      #       - .
  deploy:
    executor: heroku/default
    steps:
      - checkout
      # - attach_workspace:
      #     at: ~/frontend
      - heroku/deploy-via-git:
          force: true
                
workflows:
  build_test_deploy: 
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            # tags:
            #   only: /^v.*/
            branches:
              only: master
    
    
